# Generated by Django 5.1.6 on 2025-05-30 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_solarpanel_panel_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarplant',
            name='plant_panels',
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_panels', models.ManyToManyField(to='mainapp.solarpanel')),
                ('zone_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.solarplant')),
            ],
        ),
    ]
