# Generated by Django 5.1.6 on 2025-05-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_solarplant_plant_panels_zone'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarplant',
            name='plant_staffs',
            field=models.ManyToManyField(related_name='solarplants', to='users.member'),
        ),
    ]
