# Generated by Django 5.1.6 on 2025-05-31 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solarplant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='plant',
        ),
        migrations.DeleteModel(
            name='SolarPanel',
        ),
        migrations.DeleteModel(
            name='SolarPlant',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
