# Generated by Django 5.1.6 on 2025-04-20 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='storage/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('weather', models.CharField(choices=[('cloudy', 'Cloudy'), ('clear', 'Clear'), ('rain', 'Rain'), ('fog', 'Fog'), ('other', 'Other')], default='clear', max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('temperature', models.FloatField()),
                ('date', models.DateField()),
                ('solarplant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.solarplant')),
            ],
        ),
    ]
