# Generated by Django 5.1.6 on 2025-05-30 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('droneimage', '0001_initial'),
        ('mainapp', '0002_alter_solarpanel_panel_condition'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=99)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='droneimage.image')),
                ('solarplant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='mainapp.solarplant')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member')),
            ],
        ),
    ]
